language: rust
sudo: false

rust:
  - 1.42.0
  - 1.46.0
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

cache: cargo

script:
  - cargo build --all-features --verbose -j 1
  - cargo test  --all-features --verbose -j 1

